import type { components } from "../generated/openapi";

type Schemas = components["schemas"];

export type StoredAuth = {
  accessToken: string;
  user: AuthUser;
};

export type PaginatedResponse<T> = {
  data: T[];
  page: number;
  limit: number;
  total: number;
  totalPages: number;
};

export type MetaPaginatedResponse<T> = {
  data: T[];
  meta: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
};

export type SiteTenantResourceResponse<T = Record<string, unknown>> = {
  tenant: Tenant;
  section: SiteTenantResourceSection;
  summary: Record<string, unknown>;
  data: T[];
  meta: MetaPaginatedResponse<T>["meta"];
};

export type AuthUser = Schemas["AuthUser"];
export type AuthResponse = Schemas["AuthResponse"];
export type MfaChallengeResponse = Schemas["MfaChallengeResponse"];
export type AuthLifecycleResponse = Schemas["AuthLifecycleResponse"];
export type ProjectStatus = Schemas["ProjectStatus"];
export type ProjectStakeholderInfluence = Schemas["ProjectStakeholderInfluence"];
export type ProjectDependencyStatus = Schemas["ProjectDependencyStatus"];
export type ProjectDecisionStatus = Schemas["ProjectDecisionStatus"];
export type ProjectChangeRequestStatus = Schemas["ProjectChangeRequestStatus"];
export type TaskStatus = Schemas["TaskStatus"];
export type TaskPriority = Schemas["TaskPriority"];
export type TaskType = Schemas["TaskType"];
export type Visibility = Schemas["Visibility"];
export type DocumentStatus = Schemas["DocumentStatus"];
export type CustomFieldType = Schemas["CustomFieldType"];
export type SearchCategory = Schemas["SearchCategory"];
export type GlobalSearchResultType = Schemas["GlobalSearchResultType"];
export type GlobalSearchResult = Schemas["GlobalSearchResult"];
export type GlobalSearchResponse = Schemas["GlobalSearchResponse"];
export type Workspace = Schemas["Workspace"];
export type Team = Schemas["Team"];
export type TeamMember = Schemas["TeamMember"];
export type Permission = Schemas["Permission"];
export type Role = Schemas["Role"];
export type TenantUser = Schemas["TenantUser"];
export type BulkInviteUserInput = Schemas["BulkInviteUserInput"];
export type BulkInviteUsersResponse = Schemas["BulkInviteUsersResponse"];
export type Tenant = Schemas["Tenant"];
export type Project = Schemas["Project"];
export type ProjectMember = Schemas["ProjectMember"];
export type DocumentFolder = Schemas["DocumentFolder"];
export type WorkspaceDocument = Schemas["WorkspaceDocument"];
export type DocumentVersion = Schemas["DocumentVersion"];
export type DocumentPayload = Schemas["DocumentPayload"];
export type ProjectPermissionAction = Schemas["ProjectPermissionAction"];
export type ProjectPermissionMatrix = Schemas["ProjectPermissionMatrix"];
export type ProjectMilestone = Schemas["ProjectMilestone"];
export type ProjectRisk = Schemas["ProjectRisk"];
export type ProjectBudget = Schemas["ProjectBudget"];
export type ProjectStakeholder = Schemas["ProjectStakeholder"];
export type ProjectDependency = Schemas["ProjectDependency"];
export type ProjectDecision = Schemas["ProjectDecision"];
export type ProjectChangeRequest = Schemas["ProjectChangeRequest"];
export type UserSummary = Schemas["UserSummary"];
export type TaskLabel = Schemas["TaskLabel"];
export type TaskLabelAssignment = Schemas["TaskLabelAssignment"];
export type TaskAssignee = Schemas["TaskAssignee"];
export type TaskWatcher = Schemas["TaskWatcher"];
export type TaskDueState = Schemas["TaskDueState"];
export type TaskBoardCardSummary = Schemas["TaskBoardCardSummary"];
export type TaskBoardMetrics = Schemas["TaskBoardMetrics"];
export type TaskReferenceSummary = Schemas["TaskReferenceSummary"];
export type TaskBoardPermissions = Schemas["TaskBoardPermissions"];
export type Task = Schemas["Task"];
export type TaskTaxonomy = Schemas["TaskTaxonomy"];
export type CustomFieldOption = Schemas["CustomFieldOption"];
export type CustomField = Schemas["CustomField"];
export type TaskSavedView = Schemas["TaskSavedView"];
export type TaskComment = Schemas["TaskComment"];
export type TaskChecklistItem = Schemas["TaskChecklistItem"];
export type TaskChecklist = Schemas["TaskChecklist"];
export type TaskActivity = Schemas["TaskActivity"];
export type TaskAttachment = Schemas["TaskAttachment"];
export type FileAsset = Schemas["FileAsset"];
export type UploadIntent = Schemas["UploadIntent"];
export type TaskDependency = Schemas["TaskDependency"];
export type BoardColumn = Schemas["BoardColumn"];
export type ProjectBoard = Schemas["ProjectBoard"];
export type Sprint = Schemas["Sprint"];
export type MeetingStatus = Schemas["MeetingStatus"];
export type MeetingTypeCategory = Schemas["MeetingTypeCategory"];
export type MeetingLocationMode = Schemas["MeetingLocationMode"];
export type MeetingApprovalStatus = Schemas["MeetingApprovalStatus"];
export type MeetingAttendeeRole = Schemas["MeetingAttendeeRole"];
export type MeetingAttendeeStatus = Schemas["MeetingAttendeeStatus"];
export type MeetingAgendaStatus = Schemas["MeetingAgendaStatus"];
export type MeetingReminderChannel = Schemas["MeetingReminderChannel"];
export type MeetingReminderStatus = Schemas["MeetingReminderStatus"];
export type MeetingConferenceProvider = Schemas["MeetingConferenceProvider"];
export type MeetingReminderJobStatus = Schemas["MeetingReminderJobStatus"];
export type MeetingAvailabilityScope = Schemas["MeetingAvailabilityScope"];
export type BookingPageScope = Schemas["BookingPageScope"];
export type BookingRoutingStrategy = Schemas["BookingRoutingStrategy"];
export type BookingFormFieldType = Schemas["BookingFormFieldType"];
export type BookingRequestStatus = Schemas["BookingRequestStatus"];
export type MeetingType = Schemas["MeetingType"];
export type MeetingAttendee = Schemas["MeetingAttendee"];
export type MeetingAgendaItem = Schemas["MeetingAgendaItem"];
export type MeetingReminder = Schemas["MeetingReminder"];
export type MeetingIntegrationSettings = Schemas["MeetingIntegrationSettings"];
export type MeetingPolicy = Schemas["MeetingPolicy"];
export type MeetingAdminAnalytics = Schemas["MeetingAdminAnalytics"];
export type MeetingReminderDeliverySummary = Schemas["MeetingReminderDeliverySummary"];
export type MeetingIntegrationHealth = Schemas["MeetingIntegrationHealth"];
export type MeetingAiUsageSummary = Schemas["MeetingAiUsageSummary"];
export type MeetingAdminOverview = Schemas["MeetingAdminOverview"];
export type MeetingIntegrationStatus = Schemas["MeetingIntegrationStatus"];
export type MeetingReminderJob = Schemas["MeetingReminderJob"];
export type MeetingAiActionItem = Schemas["MeetingAiActionItem"];
export type MeetingAiState = Schemas["MeetingAiState"];
export type MeetingActivity = Schemas["MeetingActivity"];
export type MeetingDecisionStatus = Schemas["MeetingDecisionStatus"];
export type MeetingComment = Schemas["MeetingComment"];
export type MeetingDecision = Schemas["MeetingDecision"];
export type MeetingChecklistItem = Schemas["MeetingChecklistItem"];
export type Meeting = Schemas["Meeting"];
export type MeetingWorkspace = Schemas["MeetingWorkspace"];
export type MeetingAvailabilityWindow = Schemas["MeetingAvailabilityWindow"];
export type MeetingBlackoutWindow = Schemas["MeetingBlackoutWindow"];
export type MeetingAvailability = Schemas["MeetingAvailability"];
export type BookingFormField = Schemas["BookingFormField"];
export type BookingPage = Schemas["BookingPage"];
export type BookingRequest = Schemas["BookingRequest"];
export type PublicBookingSlot = Schemas["PublicBookingSlot"];
export type PublicBookingPageResponse = Schemas["PublicBookingPageResponse"];
export type PublicBookingSlotsResponse = Schemas["PublicBookingSlotsResponse"];
export type PublicBookingCreateResponse = Schemas["PublicBookingCreateResponse"];
export type NotificationChannel = Schemas["NotificationChannel"];
export type NotificationDeliveryStatus = Schemas["NotificationDeliveryStatus"];
export type NotificationDelivery = Schemas["NotificationDelivery"];
export type Notification = Schemas["Notification"];
export type NotificationPreference = Schemas["NotificationPreference"];
export type InternalMailFolder = Schemas["InternalMailFolder"];
export type InternalMailPriority = Schemas["InternalMailPriority"];
export type InternalMailRecipientKind = Schemas["InternalMailRecipientKind"];
export type InternalMailboxType = Schemas["InternalMailboxType"];
export type InternalMailboxStatus = Schemas["InternalMailboxStatus"];
export type InternalMailboxMemberRole = Schemas["InternalMailboxMemberRole"];
export type InternalMailboxAlias = Schemas["InternalMailboxAlias"];
export type InternalMailboxMember = Schemas["InternalMailboxMember"];
export type InternalMailbox = Schemas["InternalMailbox"];
export type InternalMailParticipant = Schemas["InternalMailParticipant"];
export type InternalMailRecipient = Schemas["InternalMailRecipient"];
export type InternalMailMessage = Schemas["InternalMailMessage"];
export type InternalMailThread = Schemas["InternalMailThread"];
export type InternalMailFolderSummary = Schemas["InternalMailFolderSummary"];
export type ConversationMember = Schemas["ConversationMember"];
export type MessageReaction = Schemas["MessageReaction"];
export type MessageReadReceipt = Schemas["MessageReadReceipt"];
export type MessageAttachment = Schemas["MessageAttachment"];
export type Message = Schemas["Message"];
export type Conversation = Schemas["Conversation"];
export type AuditLog = Schemas["AuditLog"];
export type AdminOverview = Schemas["AdminOverview"];
export type PlatformAdminLevel = Schemas["PlatformAdminLevel"];
export type PlatformAdminStatus = Schemas["PlatformAdminStatus"];
export type SiteAdminProfile = Schemas["SiteAdminProfile"];
export type SiteAdminOverview = Schemas["SiteAdminOverview"];
export type SiteTenantDetail = Schemas["SiteTenantDetail"];
export type SiteUserDetail = Schemas["SiteUserDetail"];
export type SiteTenantResourceSection = Schemas["SiteTenantResourceSection"];
export type SiteLoginHistory = Schemas["SiteLoginHistory"];
export type SiteTrustedDevice = Schemas["SiteTrustedDevice"];
export type SiteSsoProvider = Schemas["SiteSsoProvider"];
export type SiteSecurityPolicy = Schemas["SiteSecurityPolicy"];
export type SiteIdentitySecurityOverview = Schemas["SiteIdentitySecurityOverview"];
export type SiteSession = Schemas["SiteSession"];
export type SiteSessionsResponse = Schemas["SiteSessionsResponse"];
export type SiteBillingPlan = Schemas["SiteBillingPlan"];
export type SiteBillingFeature = Schemas["SiteBillingFeature"];
export type SiteBillingPlanPayload = Schemas["SiteBillingPlanPayload"];
export type SiteBillingFeaturePayload = Schemas["SiteBillingFeaturePayload"];
export type SitePlanFeaturePayload = Schemas["SitePlanFeaturePayload"];
export type SiteSubscription = Schemas["SiteSubscription"];
export type SiteInvoice = Schemas["SiteInvoice"];
export type SiteUsageRecord = Schemas["SiteUsageRecord"];
export type SiteBillingEvent = Schemas["SiteBillingEvent"];
export type SiteBillingOverview = Schemas["SiteBillingOverview"];
export type SiteBillingEntitlement = Schemas["SiteBillingEntitlement"];
export type BillingPlan = Schemas["BillingPlan"];
export type BillingInvoice = Schemas["BillingInvoice"];
export type BillingUsageRecord = Schemas["BillingUsageRecord"];
export type BillingEntitlementFeature = Schemas["BillingEntitlementFeature"];
export type BillingEntitlements = Schemas["BillingEntitlements"];
export type BillingAccountStatus = Schemas["BillingAccountStatus"];
export type BillingCheckoutSession = Schemas["BillingCheckoutSession"];
export type BillingPortalSession = Schemas["BillingPortalSession"];
export type BillingUsageSummary = Schemas["BillingUsageSummary"];
export type SiteIntegration = Schemas["SiteIntegration"];
export type SiteIntegrationsOverview = Schemas["SiteIntegrationsOverview"];
export type SiteWebhook = Schemas["SiteWebhook"];
export type SiteWebhookDelivery = Schemas["SiteWebhookDelivery"];
export type SiteObservabilityOverview = Schemas["SiteObservabilityOverview"];
export type SiteRealtimeSnapshot = Schemas["SiteRealtimeSnapshot"];
export type SiteRealtimeOverview = Schemas["SiteRealtimeOverview"];
export type SiteConversationMetadata = Schemas["SiteConversationMetadata"];
export type SiteMessageActivity = Schemas["SiteMessageActivity"];
export type SiteMeetingOperationsOverview = Schemas["SiteMeetingOperationsOverview"];
export type SiteMeetingTenantPosture = Schemas["SiteMeetingTenantPosture"];
export type SiteMeetingReminderLog = Schemas["SiteMeetingReminderLog"];
export type SiteComplianceOverview = Schemas["SiteComplianceOverview"];
export type SiteComplianceJob = Schemas["SiteComplianceJob"];
export type SitePlatformSearchCategory = Schemas["SitePlatformSearchCategory"];
export type SitePlatformSearchResult = Schemas["SitePlatformSearchResult"];
export type SitePlatformSearchResponse = Schemas["SitePlatformSearchResponse"];
export type SiteWorkflow = Schemas["SiteWorkflow"];
export type SiteWorkflowRun = Schemas["SiteWorkflowRun"];
export type ApprovalStatus = Schemas["ApprovalStatus"];
export type SiteApprovalDefinition = Schemas["SiteApprovalDefinition"];
export type SiteApproval = Schemas["SiteApproval"];
export type SiteWorkflowRunLog = Schemas["SiteWorkflowRunLog"];
export type SiteAutomationOverview = Schemas["SiteAutomationOverview"];
export type AiConversationStatus = Schemas["AiConversationStatus"];
export type AiActionStatus = Schemas["AiActionStatus"];
export type AiRequestStatus = Schemas["AiRequestStatus"];
export type SiteAiSettings = Schemas["SiteAiSettings"];
export type SiteAiAgent = Schemas["SiteAiAgent"];
export type SiteAiConversation = Schemas["SiteAiConversation"];
export type SiteAiAction = Schemas["SiteAiAction"];
export type SiteAiUsageLog = Schemas["SiteAiUsageLog"];
export type SiteAiOverview = Schemas["SiteAiOverview"];
export type SiteDashboard = Schemas["SiteDashboard"];
export type SiteReport = Schemas["SiteReport"];
export type SiteReportExecution = Schemas["SiteReportExecution"];
export type SiteReportExport = Schemas["SiteReportExport"];
export type SiteReportingOverview = Schemas["SiteReportingOverview"];
export type SiteHardeningOverview = Schemas["SiteHardeningOverview"];
export type PlatformAdminGrant = Schemas["PlatformAdminGrant"];
export type PlatformAuditLog = Schemas["PlatformAuditLog"];
export type SecurityChecks = Schemas["SecurityChecks"];
export type SecurityPolicy = Schemas["SecurityPolicy"];
export type IdentitySecurityOverview = Schemas["IdentitySecurityOverview"];
export type TotpSetupResponse = Schemas["TotpSetupResponse"];
export type SsoProvider = Schemas["SsoProvider"];
export type AuthSession = Schemas["AuthSession"];
export type SecurityEventSeverity = Schemas["SecurityEventSeverity"];
export type SecurityEventStatus = Schemas["SecurityEventStatus"];
export type SecurityEvent = Schemas["SecurityEvent"];
export type ComplianceJobType = Schemas["ComplianceJobType"];
export type ComplianceJobStatus = Schemas["ComplianceJobStatus"];
export type ComplianceJob = Schemas["ComplianceJob"];
export type ApiKeyStatus = Schemas["ApiKeyStatus"];
export type ApiKey = Schemas["ApiKey"];
export type CreatedApiKey = Schemas["CreatedApiKey"];
export type IntegrationProvider = Schemas["IntegrationProvider"];
export type IntegrationStatus = Schemas["IntegrationStatus"];
export type Integration = Schemas["Integration"];
export type IntegrationLog = Schemas["IntegrationLog"];
export type OmoFlowRuntimeActionItem = Schemas["OmoFlowRuntimeActionItem"];
export type OmoFlowRuntimeEvent = Schemas["OmoFlowRuntimeEvent"];
export type OmoFlowRuntimeResult = Schemas["OmoFlowRuntimeResult"];
export type WebhookDeliveryStatus = Schemas["WebhookDeliveryStatus"];
export type Webhook = Schemas["Webhook"];
export type WebhookDelivery = Schemas["WebhookDelivery"];
export type WorkflowRunStatus = Schemas["WorkflowRunStatus"];
export type WorkflowNode = Schemas["WorkflowNode"];
export type Workflow = Schemas["Workflow"];
export type WorkflowRunLog = Schemas["WorkflowRunLog"];
export type WorkflowRun = Schemas["WorkflowRun"];
export type AiSettings = Schemas["AiSettings"];
export type AiAgent = Schemas["AiAgent"];
export type ReportStatus = Schemas["ReportStatus"];
export type ReportExecutionStatus = Schemas["ReportExecutionStatus"];
export type ReportExportStatus = Schemas["ReportExportStatus"];
export type ReportExportFormat = Schemas["ReportExportFormat"];
export type Report = Schemas["Report"];
export type ReportExecution = Schemas["ReportExecution"];
export type ReportExport = Schemas["ReportExport"];
export type AnalyticsQuery = Schemas["AnalyticsQuery"];
export type AnalyticsOverview = Schemas["AnalyticsOverview"];
export type ProjectHealthAnalytics = Schemas["ProjectHealthAnalytics"];
export type TeamPerformanceAnalytics = Schemas["TeamPerformanceAnalytics"];
export type CycleTimeAnalytics = Schemas["CycleTimeAnalytics"];
export type VelocityAnalytics = Schemas["VelocityAnalytics"];
export type BudgetAnalytics = Schemas["BudgetAnalytics"];
export type SlaAnalytics = Schemas["SlaAnalytics"];
export type ModuleStatus = Schemas["ModuleStatus"];
export type ReadinessResponse = Schemas["ReadinessResponse"];
